### ISSUE TITLE
Create account in pypi to enable uploads of new pypi packages

### ISSUE THREAD

**Issue by iranzo** [petersinghanburaj/virshdumpparser#7] opened 2018-04-19 19:40 UTC
https://pypi.org/project/virshdumpparser/

**Comment by petersinghanburaj** [comment] 2018-04-20 03:47
I have created a new account in pypi (https://pypi.org/user/petersinghanburaj/).
@iranzo do I need to change the credentials mentioned in the .travis.yml file to reflect my account?
~~~
deploy:
  provider: pypi
  user: citellus
  distributions: sdist
  password:
    secure: <...>
  on:
    branch: master
~~~

**Comment by iranzo** [comment] 2018-04-22 12:13
Should not be needed, let me check

**Comment by petersinghanburaj** [comment] 2018-04-24 11:49
@iranzo the deploy is getting failed.
~~~

dpl.1
Installing deploy dependencies
Fetching: dpl-pypi-1.9.5.gem (100%)
Successfully installed dpl-pypi-1.9.5
1 gem installed
--2018-04-24 11:36:20--  https://bootstrap.pypa.io/get-pip.py
Resolving bootstrap.pypa.io (bootstrap.pypa.io)... 151.101.0.175, 151.101.64.175, 151.101.128.175, ...
Connecting to bootstrap.pypa.io (bootstrap.pypa.io)|151.101.0.175|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1642319 (1.6M) [text/x-python]
Saving to: ‘STDOUT’
100%[======================================>] 1,642,319   9.69MB/s   in 0.2s   
2018-04-24 11:36:20 (9.69 MB/s) - written to stdout [1642319/1642319]
Collecting pip
  Using cached https://files.pythonhosted.org/packages/0f/74/ecd13431bcc456ed390b44c8a6e917c1820365cbebcb6a8974d1cd045ab4/pip-10.0.1-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 9.0.1
    Uninstalling pip-9.0.1:
      Successfully uninstalled pip-9.0.1
Successfully installed pip-10.0.1
Collecting setuptools
  Downloading https://files.pythonhosted.org/packages/20/d7/04a0b689d3035143e2ff288f4b9ee4bf6ed80585cc121c90bfd85a1a8c2e/setuptools-39.0.1-py2.py3-none-any.whl (569kB)
    100% |████████████████████████████████| 573kB 3.9MB/s 
Collecting twine
  Downloading https://files.pythonhosted.org/packages/65/ae/9cfdff186dd4812c59bad890435538858f13fe43dbe6923e0fb20f0adfc8/twine-1.11.0-py2.py3-none-any.whl
Collecting wheel
  Using cached https://files.pythonhosted.org/packages/1b/d2/22cde5ea9af055f81814f9f2545f5ed8a053eb749c08d186b369959189a8/wheel-0.31.0-py2.py3-none-any.whl
Collecting pkginfo>=1.4.2 (from twine)
  Downloading https://files.pythonhosted.org/packages/a3/fe/f32a48d48f40a7209be9825fba2566cab92364787cf37de2e08300dd6ce7/pkginfo-1.4.2-py2.py3-none-any.whl
Requirement not upgraded as not directly required: requests!=2.15,!=2.16,>=2.5.0 in /home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages (from twine) (2.18.4)
Collecting tqdm>=4.14 (from twine)
  Downloading https://files.pythonhosted.org/packages/78/bc/de067ab2d700b91717dc5459d86a1877e2df31abfb90ab01a5a5a5ce30b4/tqdm-4.23.0-py2.py3-none-any.whl (42kB)
    100% |████████████████████████████████| 51kB 7.8MB/s 
Collecting requests-toolbelt>=0.8.0 (from twine)
  Downloading https://files.pythonhosted.org/packages/97/8a/d710f792d6f6ecc089c5e55b66e66c3f2f35516a1ede5a8f54c13350ffb0/requests_toolbelt-0.8.0-py2.py3-none-any.whl (54kB)
    100% |████████████████████████████████| 61kB 7.4MB/s 
Requirement not upgraded as not directly required: chardet<3.1.0,>=3.0.2 in /home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages (from requests!=2.15,!=2.16,>=2.5.0->twine) (3.0.4)
Requirement not upgraded as not directly required: certifi>=2017.4.17 in /home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages (from requests!=2.15,!=2.16,>=2.5.0->twine) (2018.4.16)
Requirement not upgraded as not directly required: urllib3<1.23,>=1.21.1 in /home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages (from requests!=2.15,!=2.16,>=2.5.0->twine) (1.22)
Requirement not upgraded as not directly required: idna<2.7,>=2.5 in /home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages (from requests!=2.15,!=2.16,>=2.5.0->twine) (2.6)
Installing collected packages: setuptools, pkginfo, tqdm, requests-toolbelt, twine, wheel
  Found existing installation: setuptools 38.5.1
    Uninstalling setuptools-38.5.1:
      Successfully uninstalled setuptools-38.5.1
  Found existing installation: wheel 0.30.0
    Uninstalling wheel-0.30.0:
      Successfully uninstalled wheel-0.30.0
Successfully installed pkginfo-1.4.2 requests-toolbelt-0.8.0 setuptools-39.0.1 tqdm-4.23.0 twine-1.11.0 wheel-0.31.0
dpl.2
Preparing deploy
Authenticated as citellus
Cleaning up git repository with `git stash --all`. If you need build artifacts for deployment, set `deploy.skip_cleanup: true`. See https://docs.travis-ci.com/user/deployment#Uploading-Files-and-skip_cleanup.
Saved working directory and index state WIP on (no branch): 0e9b6e5 Merge pull request #11 from iranzo/patch-3
dpl.3
Deploying application
running sdist
running egg_info
creating virshdumpparser.egg-info
writing requirements to virshdumpparser.egg-info/requires.txt
writing top-level names to virshdumpparser.egg-info/top_level.txt
writing entry points to virshdumpparser.egg-info/entry_points.txt
writing virshdumpparser.egg-info/PKG-INFO
writing dependency_links to virshdumpparser.egg-info/dependency_links.txt
writing manifest file 'virshdumpparser.egg-info/SOURCES.txt'
reading manifest file 'virshdumpparser.egg-info/SOURCES.txt'
writing manifest file 'virshdumpparser.egg-info/SOURCES.txt'
running check
creating virshdumpparser-0.1
creating virshdumpparser-0.1/virshdumpparser
creating virshdumpparser-0.1/virshdumpparser.egg-info
copying files to virshdumpparser-0.1...
copying README.md -> virshdumpparser-0.1
copying setup.py -> virshdumpparser-0.1
copying virshdumpparser/__init__.py -> virshdumpparser-0.1/virshdumpparser
copying virshdumpparser/cli.py -> virshdumpparser-0.1/virshdumpparser
copying virshdumpparser/parser.py -> virshdumpparser-0.1/virshdumpparser
copying virshdumpparser.egg-info/PKG-INFO -> virshdumpparser-0.1/virshdumpparser.egg-info
copying virshdumpparser.egg-info/SOURCES.txt -> virshdumpparser-0.1/virshdumpparser.egg-info
copying virshdumpparser.egg-info/dependency_links.txt -> virshdumpparser-0.1/virshdumpparser.egg-info
copying virshdumpparser.egg-info/entry_points.txt -> virshdumpparser-0.1/virshdumpparser.egg-info
copying virshdumpparser.egg-info/requires.txt -> virshdumpparser-0.1/virshdumpparser.egg-info
copying virshdumpparser.egg-info/top_level.txt -> virshdumpparser-0.1/virshdumpparser.egg-info
Writing virshdumpparser-0.1/setup.cfg
creating dist
Creating tar archive
removing 'virshdumpparser-0.1' (and everything under it)
Uploading distributions to https://upload.pypi.org/legacy/
Uploading virshdumpparser-0.1.tar.gz
100%|██████████████████████████████████████| 6.84k/6.84k [00:01<00:00, 6.22kB/s]
HTTPError: 403 Client Error: Invalid or non-existent authentication information. for url: https://upload.pypi.org/legacy/
virshdumpparser.egg-info/PKG-INFO already exists, no checkout
virshdumpparser.egg-info/SOURCES.txt already exists, no checkout
virshdumpparser.egg-info/dependency_links.txt already exists, no checkout
virshdumpparser.egg-info/entry_points.txt already exists, no checkout
virshdumpparser.egg-info/requires.txt already exists, no checkout
virshdumpparser.egg-info/top_level.txt already exists, no checkout
Could not restore untracked files from stash entry
PyPI upload failed.
failed to deploy
~~~

Should I try with my account credentials in .travis.yml file.

**Comment by petersinghanburaj** [comment] 2018-05-09 13:54
The issue is resolved after updating the user credentials.

**Closed by petersinghanburaj** 2018-05-09 13:54 UTC
